include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_function_literals_in_foreach_calls: false
    curly_braces_in_flow_control_structures: false
    depend_on_referenced_packages: false
    non_constant_identifier_names: false
    constant_identifier_names: false
