List<String> SEARCH_MOVIES_PLACEHOLDER = [
  'El club de la lucha',
  'Mystic River',
  'El club de los poetas muertos',
  'El padrino',
  'Érase una vez en Hollywood',
  'El señor de los anillos',
  'Harry Potter y la piedra filosofal',
  'Pulp Fiction',
  'El caballero oscuro',
  'El silencio de los corderos',
  'V de Vendetta',
  'Gladiator',
  'El rey león',
  'El Pianista',
  'El gran Lebowski',
  'El sexto sentido',
  'El lobo de Wall Street',
  'Forrest Gump',
  'Malditos bastardos',
  'Seven',
  'Invictus',
  'El indomable Will Hunting',
  'El precio del poder',
  'La vida es bella',
  'El truco final',
  'Los intocables de Eliot Ness',
  'Gran Torino',
  'Los puentes de Madison',
  'Los otros',
  'Trainspotting',
  'Training Day',
  'Infiltrados',
  'Ciudad de Dios',
  'Origen',
  'Shutter Island',
  'Los juegos del hambre',
  'El curioso caso de Benjamin Button',
  'El aviador',
  'Atrápame si puedes',
  'Los vengadores',
  'El caballero oscuro: La leyenda renace',
  'El hobbit',
  'El señor de los anillos: El retorno del rey',
  'El diario de Noa',
];
