/// Flutter icons MaterialDesignIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MaterialDesignIcons
///      fonts:
///       - asset: fonts/MaterialDesignIcons.ttf
///
///
///
library;

import 'package:flutter/widgets.dart';

class MaterialDesignIcons {
  MaterialDesignIcons._();

  static const _kFontFam = 'MaterialDesignIcons';
  static const String? _kFontPkg = null;

  static const IconData emoticonConfusedOutline =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
